"""New table price

Revision ID: d9c39fbb39fb
Revises: 
Create Date: 2022-05-27 11:18:10.107690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c39fbb39fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('ticker_name', sa.String(length=10), nullable=False),
    sa.Column('trading_day', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.FLOAT(), nullable=False),
    sa.Column('max_price', sa.FLOAT(), nullable=False),
    sa.Column('min_price', sa.FLOAT(), nullable=False),
    sa.Column('close_price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__price_history')),
    sa.UniqueConstraint('id', name=op.f('uq__price_history__id')),
    sa.UniqueConstraint('ticker_name', name=op.f('uq__price_history__ticker_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    # ### end Alembic commands ###
